sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.1'
  - 'stable'
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
  firefox: 'latest-esr'
cache:
  directories:
  - node_modules
env:
  matrix:
    - EMBER_TRY_SCENARIO=ember-2-3
    - EMBER_TRY_SCENARIO=ember-2-8
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-release
  global:
    - CXX=g++-4.8
    - secure: aYhypFwtm1Suv1kTISjEjoDcz+XeWzWAvt05p59bMr+vKeEwX4Gu3AK/CgtMAJKMOOrOAuMvGBWF0D+IctuVxjzBevG7cenO0OK+iqGc2a6iJVhnQCGfVjlMRt/rIh+g1Uqbh3cZA5jW2+rBcoIbKmwWuJG2da7fp5Wp+6qVK0PO+DxLeA8hRY61mcmY2eEEu5ObmushX9mIivkVAg6emaNmODdqZaYNDgyxkkeYTfJOFyZIdXe4BjHP/GYmxJnuTI5yGTl+TIG3SGMP/36ht4pGXhg5u1KZgHNr3rxQEctlE8nliD8k/Lhr3c4VRrZ0B2rfLP6TeQdl8KW16PPtDCEC64vOF6lJe08w2K//3mLOAqwH2IOHtjpgX42hNHjnLUHjzqc6Y54pk6Vpe7IZpaPkaz3vQyGHsZ7+KTELmnv+3F+nHR1mA2XE3/keXXLJgR7H3VGFr64Sl3kH1hpeIzvAE9hIzmZPFcA0jbaFjUA4f5KUEeMAxO3EzSefBZ2o9D7zxFs+tnKC0pT46ba1qZAU9hzo9+Lyv01BrpC935i2Z5Qspm72s0ht6oopaZ68o5bPdvrOq5enqdk2sLseGYEJCh+0yuoyfAuarpvZk9ucBxiRIXZcxpIZ36l8NH/1x7fvj7r5mKf2sePnQ2Y1s4Jg8iIGC7B7TLwKoqPwIdg=
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release
before_install:
  - npm config set spin false
  - npm install -g coveralls pr-bumper@^1.0.0
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh
install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - .travis/maybe-bump-version.sh
after_success:
  - .travis/maybe-publish-coverage.sh
  - .travis/maybe-publish-gh-pages.sh
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: ESPMbZwhsrfGfO/p+f5ykZFWImTxNHe8Wab2+EZge87P8ZojO0JhkpnpCM8p9mrHOz+gp2exzGViyjS1FoIRw8yr0kV2fbuCUhZy014nft9WtGnwGs/f9y7odFBOGIlRg4i23VtRjKtE9xsNdS6bOORtxg6IK/b9l25sd+dEhhPG29HkWmGGnjCeWFGTRum0jF7HMCRAp1FSKvELIdDegBs9qxMuv5yu5ozGRyjufwXRSkWd9o0FQDTweJPqGF+izkf5am8q0jbYRlZdUBCMw4Ew4bhtmx1oDOmUO+WgPUCPzfXirvwsMTQaaK2em5PIF78S2yQNh8PTziRcOOMmXGnKmZwcypsQ2Bd6GDOOG6vsXZ9cMpWpnCpPPx44bR2jwuwUrSfjSPv3OJgZIo4RP75NIPv46tST0JdFqth+kEBtCzHNgpQWyBUUFIyoqSjkTKk4WHA/JVHIrOamp0WoZnG/e9CwuC3IXh4fIlyjI6rTMjP9U82Z+rxNmk149WoQ9ilYqlcVv+xUjQsb4zRda7LGeHGzG5f4onwdv4Pg0BiHkKAwYLClwV1GAK6+oQsyw2jpyW4dRuR79zp0dw+cluad78x4mKhqJkf5HmqTsrwDdfAn27WzOW8YT12iaULnn/IE1xBfVNEp8AqMUAxPcEUjusOx3o+TAb4m9ale7cg=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '6.9.1'
    tags: true
notifications:
  slack:
    secure: GzRGMb3myLs+tzUB4L0ZfOoR9IX6u/Ulr6aqeNImlOKeMAPU/fJ9H4Pb1ReQ2wnIZBTtY0N7C/egbEEhBaLA+6DQR2cJ204kHyotrd4GiI2Jb0JIWtZ71RxyM6kFhW6X+jy8kdsAb8gs+q277CiopBRm1bXSHT5SAhpm83ArgJFJFFagWmxKW7YBl28d2/efpm5BSqQ4jMKHeLwarrpv666bvWnPI7bJSY7q6c6JK4Pv/89tmp5CsZFCXRnAWITER/kgCd/2bj02lKaMNaugiZAzL+j92YobpAfAp8jP6JbFwwRHSZiPo5HZH4IitlE1Ccvb/xrNzy5vtOiu0JdZVc4NfkHwaJezOQP8gPHmalTORTWddeZAATGCvmz9xmYRNDbqtAHo0WjKbzPkBnYMn+IYrWNz8gb0pS1zRZXPFHSKusr5+i/3xQv+q/thSoKkuEnibvb3+tlydO++GaI1YaoUhfY70OeuLF9CIBovLwmj/5QRhXKjFArqIzjaV1DQrSVxpOa8nnvc1w5cw+JQaabSvIP8ln0P3D68JEtJ67Mx2itapWhn1VfSgkT/Bwx3AONvsZ+/R/rGFMDe8t5nqUMKYcCwdboOzG/eqMKpPQ3j2QeNGD/Dp9zWNwdMZVIIhcRpj2E547KewOpZmF+VbbAfHxRQChn9kcvRDP+Wuoc=
